version: "3.7"

services:
  db:
    image: mariadb:10.3.31
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - magento-net

  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    image: magento
    container_name: magento-local
    privileged: true
    ports:
      - "8082:80"
    volumes:
      - ".:/var/www/html"
    networks:
      - magento-net

volumes:
  db_data:

networks:
  magento-net:
    driver: bridge
